// Auto-generated main exports
// This file is generated by convert-icons.js - do not edit manually

export { default as AcademicCap } from './filled/AcademicCap';
export { default as AdjustmentsHorizontal } from './filled/AdjustmentsHorizontal';
export { default as Adjustments } from './filled/Adjustments';
export { default as Annotation } from './filled/Annotation';
export { default as ArchiveBoxArrowDown } from './filled/ArchiveBoxArrowDown';
export { default as ArchiveBoxXMark } from './filled/ArchiveBoxXMark';
export { default as Archive } from './filled/Archive';
export { default as ArrowCircleDown } from './filled/ArrowCircleDown';
export { default as ArrowCircleLeft } from './filled/ArrowCircleLeft';
export { default as ArrowCircleRight } from './filled/ArrowCircleRight';
export { default as ArrowCircleUp } from './filled/ArrowCircleUp';
export { default as ArrowDown } from './filled/ArrowDown';
export { default as ArrowLeft } from './filled/ArrowLeft';
export { default as ArrowNarrowDown } from './filled/ArrowNarrowDown';
export { default as ArrowNarrowLeft } from './filled/ArrowNarrowLeft';
export { default as ArrowNarrowRight } from './filled/ArrowNarrowRight';
export { default as ArrowNarrowUp } from './filled/ArrowNarrowUp';
export { default as ArrowRight } from './filled/ArrowRight';
export { default as ArrowSmDown } from './filled/ArrowSmDown';
export { default as ArrowSmLeft } from './filled/ArrowSmLeft';
export { default as ArrowSmRight } from './filled/ArrowSmRight';
export { default as ArrowSmUp } from './filled/ArrowSmUp';
export { default as ArrowTopRightOnSquare } from './filled/ArrowTopRightOnSquare';
export { default as ArrowUpOnSquareStack } from './filled/ArrowUpOnSquareStack';
export { default as ArrowUpOnSquare } from './filled/ArrowUpOnSquare';
export { default as ArrowUpRight } from './filled/ArrowUpRight';
export { default as ArrowUp } from './filled/ArrowUp';
export { default as ArrowUturnDown } from './filled/ArrowUturnDown';
export { default as ArrowUturnRight } from './filled/ArrowUturnRight';
export { default as ArrowUturnUp } from './filled/ArrowUturnUp';
export { default as ArrowsExpand } from './filled/ArrowsExpand';
export { default as ArrowsPointingIn } from './filled/ArrowsPointingIn';
export { default as AtSymbol } from './filled/AtSymbol';
export { default as Backspace } from './filled/Backspace';
export { default as BadgeCheck } from './filled/BadgeCheck';
export { default as Ban } from './filled/Ban';
export { default as Banknotes } from './filled/Banknotes';
export { default as Bars4 } from './filled/Bars4';
export { default as Battery0 } from './filled/Battery0';
export { default as Battery100 } from './filled/Battery100';
export { default as Battery50 } from './filled/Battery50';
export { default as Beaker } from './filled/Beaker';
export { default as BellAlert } from './filled/BellAlert';
export { default as BellSlash } from './filled/BellSlash';
export { default as BellSnooze } from './filled/BellSnooze';
export { default as Bell } from './filled/Bell';
export { default as BoltSlash } from './filled/BoltSlash';
export { default as BookOpen } from './filled/BookOpen';
export { default as BookmarkAlt } from './filled/BookmarkAlt';
export { default as BookmarkSlash } from './filled/BookmarkSlash';
export { default as Bookmark } from './filled/Bookmark';
export { default as Briefcase } from './filled/Briefcase';
export { default as BugAnt } from './filled/BugAnt';
export { default as BuildingOffice2 } from './filled/BuildingOffice2';
export { default as BuildingOffice } from './filled/BuildingOffice';
export { default as BuildingStorefront } from './filled/BuildingStorefront';
export { default as Cake } from './filled/Cake';
export { default as Calculator } from './filled/Calculator';
export { default as CalendarDays } from './filled/CalendarDays';
export { default as Calendar } from './filled/Calendar';
export { default as Camera } from './filled/Camera';
export { default as Cash } from './filled/Cash';
export { default as ChartBarSquare } from './filled/ChartBarSquare';
export { default as ChartBar } from './filled/ChartBar';
export { default as ChartPie } from './filled/ChartPie';
export { default as ChatAlt } from './filled/ChatAlt';
export { default as ChatBubbleBottomCenterText } from './filled/ChatBubbleBottomCenterText';
export { default as ChatBubbleBottomCenter } from './filled/ChatBubbleBottomCenter';
export { default as ChatBubbleLeftEllipsis } from './filled/ChatBubbleLeftEllipsis';
export { default as ChatBubbleLeftRight } from './filled/ChatBubbleLeftRight';
export { default as ChatBubbleLeft } from './filled/ChatBubbleLeft';
export { default as ChatBubbleOvalLeft } from './filled/ChatBubbleOvalLeft';
export { default as Chat } from './filled/Chat';
export { default as CheckCircle } from './filled/CheckCircle';
export { default as Check } from './filled/Check';
export { default as ChevronDoubleDown } from './filled/ChevronDoubleDown';
export { default as ChevronDoubleLeft } from './filled/ChevronDoubleLeft';
export { default as ChevronDoubleRight } from './filled/ChevronDoubleRight';
export { default as ChevronDoubleUp } from './filled/ChevronDoubleUp';
export { default as ChevronDown } from './filled/ChevronDown';
export { default as ChevronLeft } from './filled/ChevronLeft';
export { default as ChevronRight } from './filled/ChevronRight';
export { default as ChevronUp } from './filled/ChevronUp';
export { default as Chip } from './filled/Chip';
export { default as ClipboardCheck } from './filled/ClipboardCheck';
export { default as ClipboardCopy } from './filled/ClipboardCopy';
export { default as ClipboardDocumentCheck } from './filled/ClipboardDocumentCheck';
export { default as ClipboardDocumentList } from './filled/ClipboardDocumentList';
export { default as ClipboardDocument } from './filled/ClipboardDocument';
export { default as ClipboardList } from './filled/ClipboardList';
export { default as Clock } from './filled/Clock';
export { default as CloudDownload } from './filled/CloudDownload';
export { default as CloudUpload } from './filled/CloudUpload';
export { default as Cloud } from './filled/Cloud';
export { default as CodeBracketSquare } from './filled/CodeBracketSquare';
export { default as Code } from './filled/Code';
export { default as Cog6Tooth } from './filled/Cog6Tooth';
export { default as Cog8Tooth } from './filled/Cog8Tooth';
export { default as Cog } from './filled/Cog';
export { default as Collection } from './filled/Collection';
export { default as ColorSwatch } from './filled/ColorSwatch';
export { default as CreditCard1 } from './filled/CreditCard1';
export { default as CreditCard } from './filled/CreditCard';
export { default as CubeTransparent } from './filled/CubeTransparent';
export { default as Cube } from './filled/Cube';
export { default as CurrencyBangladeshi } from './filled/CurrencyBangladeshi';
export { default as CurrencyDollar } from './filled/CurrencyDollar';
export { default as CurrencyEuro } from './filled/CurrencyEuro';
export { default as CurrencyPound } from './filled/CurrencyPound';
export { default as CurrencyRupee } from './filled/CurrencyRupee';
export { default as CurrencyYen } from './filled/CurrencyYen';
export { default as CursorArrowRipple } from './filled/CursorArrowRipple';
export { default as CursorClick } from './filled/CursorClick';
export { default as Database } from './filled/Database';
export { default as DesktopComputer } from './filled/DesktopComputer';
export { default as DeviceIpad } from './filled/DeviceIpad';
export { default as DeviceMobile } from './filled/DeviceMobile';
export { default as DocumentAdd } from './filled/DocumentAdd';
export { default as DocumentCheck } from './filled/DocumentCheck';
export { default as DocumentDownload } from './filled/DocumentDownload';
export { default as DocumentDuplicate } from './filled/DocumentDuplicate';
export { default as DocumentRemove } from './filled/DocumentRemove';
export { default as DocumentReport } from './filled/DocumentReport';
export { default as DocumentSearch } from './filled/DocumentSearch';
export { default as DocumentText } from './filled/DocumentText';
export { default as DocumentUpload } from './filled/DocumentUpload';
export { default as Document } from './filled/Document';
export { default as DotsCircleHorizontal } from './filled/DotsCircleHorizontal';
export { default as DotsHorizontal } from './filled/DotsHorizontal';
export { default as DotsVertical } from './filled/DotsVertical';
export { default as Download } from './filled/Download';
export { default as Duplicate } from './filled/Duplicate';
export { default as EllipsisHorizontalCircle } from './filled/EllipsisHorizontalCircle';
export { default as EmojiHappy } from './filled/EmojiHappy';
export { default as EmojiSad } from './filled/EmojiSad';
export { default as ExclamationCircle } from './filled/ExclamationCircle';
export { default as Exclamation } from './filled/Exclamation';
export { default as ExternalLink } from './filled/ExternalLink';
export { default as EyeDropper } from './filled/EyeDropper';
export { default as EyeOff } from './filled/EyeOff';
export { default as Eye } from './filled/Eye';
export { default as FastForward } from './filled/FastForward';
export { default as Film } from './filled/Film';
export { default as Filter } from './filled/Filter';
export { default as FingerPrint } from './filled/FingerPrint';
export { default as Fire } from './filled/Fire';
export { default as Flag } from './filled/Flag';
export { default as FolderAdd } from './filled/FolderAdd';
export { default as FolderDownload } from './filled/FolderDownload';
export { default as FolderRemove } from './filled/FolderRemove';
export { default as Folder } from './filled/Folder';
export { default as Gif } from './filled/Gif';
export { default as Gift } from './filled/Gift';
export { default as GlobeAlt } from './filled/GlobeAlt';
export { default as GlobeAmericas } from './filled/GlobeAmericas';
export { default as GlobeAsiaAustralia } from './filled/GlobeAsiaAustralia';
export { default as GlobeEuropeAfrica } from './filled/GlobeEuropeAfrica';
export { default as Globe } from './filled/Globe';
export { default as Hand } from './filled/Hand';
export { default as Hashtag } from './filled/Hashtag';
export { default as Heart } from './filled/Heart';
export { default as History } from './filled/History';
export { default as HomeModern } from './filled/HomeModern';
export { default as Home } from './filled/Home';
export { default as Identification21 } from './filled/Identification21';
export { default as Identification2 } from './filled/Identification2';
export { default as InboxIn } from './filled/InboxIn';
export { default as InboxStack } from './filled/InboxStack';
export { default as Inbox } from './filled/Inbox';
export { default as InformationCircle } from './filled/InformationCircle';
export { default as Key } from './filled/Key';
export { default as LightBulb } from './filled/LightBulb';
export { default as LightningBolt } from './filled/LightningBolt';
export { default as Link } from './filled/Link';
export { default as LocationMarker } from './filled/LocationMarker';
export { default as LockClosed } from './filled/LockClosed';
export { default as LockOpen } from './filled/LockOpen';
export { default as LogoutLeft } from './filled/LogoutLeft';
export { default as LogoutRight } from './filled/LogoutRight';
export { default as MailOpen } from './filled/MailOpen';
export { default as Mail } from './filled/Mail';
export { default as Map1 } from './filled/Map1';
export { default as MapPin } from './filled/MapPin';
export { default as Map } from './filled/Map';
export { default as MdLibrary } from './filled/MdLibrary';
export { default as MenuAlt1 } from './filled/MenuAlt1';
export { default as MenuAlt2 } from './filled/MenuAlt2';
export { default as MenuAlt3 } from './filled/MenuAlt3';
export { default as MenuAlt4 } from './filled/MenuAlt4';
export { default as Menu } from './filled/Menu';
export { default as Microphone } from './filled/Microphone';
export { default as MinusCircle } from './filled/MinusCircle';
export { default as MinusSm } from './filled/MinusSm';
export { default as Minus } from './filled/Minus';
export { default as Moon } from './filled/Moon';
export { default as MusicNote } from './filled/MusicNote';
export { default as Newspaper } from './filled/Newspaper';
export { default as Next } from './filled/Next';
export { default as OfficeBuilding } from './filled/OfficeBuilding';
export { default as PaintBrush } from './filled/PaintBrush';
export { default as PaperAirplane1 } from './filled/PaperAirplane1';
export { default as PaperAirplane } from './filled/PaperAirplane';
export { default as PaperClip } from './filled/PaperClip';
export { default as PauseCircle } from './filled/PauseCircle';
export { default as Pause } from './filled/Pause';
export { default as PencilAlt } from './filled/PencilAlt';
export { default as Pencil } from './filled/Pencil';
export { default as PhoneIncoming } from './filled/PhoneIncoming';
export { default as PhoneOutgoing } from './filled/PhoneOutgoing';
export { default as PhoneXMark } from './filled/PhoneXMark';
export { default as Phone } from './filled/Phone';
export { default as Photograph } from './filled/Photograph';
export { default as PlayCircle } from './filled/PlayCircle';
export { default as PlayPause } from './filled/PlayPause';
export { default as Play } from './filled/Play';
export { default as PlusCircle } from './filled/PlusCircle';
export { default as PlusSm } from './filled/PlusSm';
export { default as Plus } from './filled/Plus';
export { default as Power } from './filled/Power';
export { default as PresentationChartBar } from './filled/PresentationChartBar';
export { default as PresentationChartLine } from './filled/PresentationChartLine';
export { default as Printer } from './filled/Printer';
export { default as Puzzle } from './filled/Puzzle';
export { default as QrCode2 } from './filled/QrCode2';
export { default as Qrcode } from './filled/Qrcode';
export { default as QuestionMarkCircle } from './filled/QuestionMarkCircle';
export { default as QueueList } from './filled/QueueList';
export { default as Radio } from './filled/Radio';
export { default as ReceiptRefund } from './filled/ReceiptRefund';
export { default as ReceiptTax } from './filled/ReceiptTax';
export { default as RectangleGroup } from './filled/RectangleGroup';
export { default as RefreshReply } from './filled/RefreshReply';
export { default as Refresh } from './filled/Refresh';
export { default as Reply } from './filled/Reply';
export { default as Rewind } from './filled/Rewind';
export { default as RocketLaunch } from './filled/RocketLaunch';
export { default as Rss } from './filled/Rss';
export { default as SaveAs } from './filled/SaveAs';
export { default as Save } from './filled/Save';
export { default as Scale } from './filled/Scale';
export { default as Scissors } from './filled/Scissors';
export { default as SearchCircle } from './filled/SearchCircle';
export { default as Search } from './filled/Search';
export { default as Selector } from './filled/Selector';
export { default as ServerStack } from './filled/ServerStack';
export { default as Server } from './filled/Server';
export { default as Share } from './filled/Share';
export { default as ShieldCheck } from './filled/ShieldCheck';
export { default as ShieldExclamation } from './filled/ShieldExclamation';
export { default as ShoppingBag } from './filled/ShoppingBag';
export { default as ShoppingCart } from './filled/ShoppingCart';
export { default as SortAscending } from './filled/SortAscending';
export { default as SortDescending } from './filled/SortDescending';
export { default as Sparkles } from './filled/Sparkles';
export { default as Speakerphone } from './filled/Speakerphone';
export { default as Star } from './filled/Star';
export { default as StatusOffline } from './filled/StatusOffline';
export { default as StatusOnline } from './filled/StatusOnline';
export { default as Stop1 } from './filled/Stop1';
export { default as Stop } from './filled/Stop';
export { default as Sun } from './filled/Sun';
export { default as Support } from './filled/Support';
export { default as SwitchHorizontal } from './filled/SwitchHorizontal';
export { default as SwitchVertical } from './filled/SwitchVertical';
export { default as TableCells2 } from './filled/TableCells2';
export { default as Table } from './filled/Table';
export { default as Tag } from './filled/Tag';
export { default as Template } from './filled/Template';
export { default as Terminal } from './filled/Terminal';
export { default as ThumbDown } from './filled/ThumbDown';
export { default as ThumbUp } from './filled/ThumbUp';
export { default as Ticket } from './filled/Ticket';
export { default as Translate } from './filled/Translate';
export { default as Trash } from './filled/Trash';
export { default as TrendingDown } from './filled/TrendingDown';
export { default as TrendingUp } from './filled/TrendingUp';
export { default as Trophy } from './filled/Trophy';
export { default as Truck1 } from './filled/Truck1';
export { default as Truck } from './filled/Truck';
export { default as Tv } from './filled/Tv';
export { default as Upload } from './filled/Upload';
export { default as UserAdd } from './filled/UserAdd';
export { default as UserCircle } from './filled/UserCircle';
export { default as UserGroup } from './filled/UserGroup';
export { default as UserRemove } from './filled/UserRemove';
export { default as User } from './filled/User';
export { default as Users } from './filled/Users';
export { default as Variable } from './filled/Variable';
export { default as VideoCameraSlash } from './filled/VideoCameraSlash';
export { default as VideoCamera } from './filled/VideoCamera';
export { default as ViewBoards } from './filled/ViewBoards';
export { default as ViewGridAdd } from './filled/ViewGridAdd';
export { default as ViewGrid } from './filled/ViewGrid';
export { default as ViewList } from './filled/ViewList';
export { default as ViewfinderDot } from './filled/ViewfinderDot';
export { default as VolumeOff } from './filled/VolumeOff';
export { default as VolumeUp } from './filled/VolumeUp';
export { default as Wallet } from './filled/Wallet';
export { default as Wifi } from './filled/Wifi';
export { default as Window } from './filled/Window';
export { default as WrenchScrewdriver } from './filled/WrenchScrewdriver';
export { default as Wrench } from './filled/Wrench';
export { default as XCircle } from './filled/XCircle';
export { default as X } from './filled/X';
export { default as ZoomIn } from './filled/ZoomIn';
export { default as ZoomOut } from './filled/ZoomOut';

// Export all filled icons as a group
export * as FilledIcons from './filled';

// Export individual categories (can be extended)
export * from './filled';

// Export types for convenience
export type { SVGProps } from 'react';

// Default export with all icons
export default {
  AcademicCap: require('./filled/AcademicCap'),
  AdjustmentsHorizontal: require('./filled/AdjustmentsHorizontal'),
  Adjustments: require('./filled/Adjustments'),
  Annotation: require('./filled/Annotation'),
  ArchiveBoxArrowDown: require('./filled/ArchiveBoxArrowDown'),
  ArchiveBoxXMark: require('./filled/ArchiveBoxXMark'),
  Archive: require('./filled/Archive'),
  ArrowCircleDown: require('./filled/ArrowCircleDown'),
  ArrowCircleLeft: require('./filled/ArrowCircleLeft'),
  ArrowCircleRight: require('./filled/ArrowCircleRight'),
  ArrowCircleUp: require('./filled/ArrowCircleUp'),
  ArrowDown: require('./filled/ArrowDown'),
  ArrowLeft: require('./filled/ArrowLeft'),
  ArrowNarrowDown: require('./filled/ArrowNarrowDown'),
  ArrowNarrowLeft: require('./filled/ArrowNarrowLeft'),
  ArrowNarrowRight: require('./filled/ArrowNarrowRight'),
  ArrowNarrowUp: require('./filled/ArrowNarrowUp'),
  ArrowRight: require('./filled/ArrowRight'),
  ArrowSmDown: require('./filled/ArrowSmDown'),
  ArrowSmLeft: require('./filled/ArrowSmLeft'),
  ArrowSmRight: require('./filled/ArrowSmRight'),
  ArrowSmUp: require('./filled/ArrowSmUp'),
  ArrowTopRightOnSquare: require('./filled/ArrowTopRightOnSquare'),
  ArrowUpOnSquareStack: require('./filled/ArrowUpOnSquareStack'),
  ArrowUpOnSquare: require('./filled/ArrowUpOnSquare'),
  ArrowUpRight: require('./filled/ArrowUpRight'),
  ArrowUp: require('./filled/ArrowUp'),
  ArrowUturnDown: require('./filled/ArrowUturnDown'),
  ArrowUturnRight: require('./filled/ArrowUturnRight'),
  ArrowUturnUp: require('./filled/ArrowUturnUp'),
  ArrowsExpand: require('./filled/ArrowsExpand'),
  ArrowsPointingIn: require('./filled/ArrowsPointingIn'),
  AtSymbol: require('./filled/AtSymbol'),
  Backspace: require('./filled/Backspace'),
  BadgeCheck: require('./filled/BadgeCheck'),
  Ban: require('./filled/Ban'),
  Banknotes: require('./filled/Banknotes'),
  Bars4: require('./filled/Bars4'),
  Battery0: require('./filled/Battery0'),
  Battery100: require('./filled/Battery100'),
  Battery50: require('./filled/Battery50'),
  Beaker: require('./filled/Beaker'),
  BellAlert: require('./filled/BellAlert'),
  BellSlash: require('./filled/BellSlash'),
  BellSnooze: require('./filled/BellSnooze'),
  Bell: require('./filled/Bell'),
  BoltSlash: require('./filled/BoltSlash'),
  BookOpen: require('./filled/BookOpen'),
  BookmarkAlt: require('./filled/BookmarkAlt'),
  BookmarkSlash: require('./filled/BookmarkSlash'),
  Bookmark: require('./filled/Bookmark'),
  Briefcase: require('./filled/Briefcase'),
  BugAnt: require('./filled/BugAnt'),
  BuildingOffice2: require('./filled/BuildingOffice2'),
  BuildingOffice: require('./filled/BuildingOffice'),
  BuildingStorefront: require('./filled/BuildingStorefront'),
  Cake: require('./filled/Cake'),
  Calculator: require('./filled/Calculator'),
  CalendarDays: require('./filled/CalendarDays'),
  Calendar: require('./filled/Calendar'),
  Camera: require('./filled/Camera'),
  Cash: require('./filled/Cash'),
  ChartBarSquare: require('./filled/ChartBarSquare'),
  ChartBar: require('./filled/ChartBar'),
  ChartPie: require('./filled/ChartPie'),
  ChatAlt: require('./filled/ChatAlt'),
  ChatBubbleBottomCenterText: require('./filled/ChatBubbleBottomCenterText'),
  ChatBubbleBottomCenter: require('./filled/ChatBubbleBottomCenter'),
  ChatBubbleLeftEllipsis: require('./filled/ChatBubbleLeftEllipsis'),
  ChatBubbleLeftRight: require('./filled/ChatBubbleLeftRight'),
  ChatBubbleLeft: require('./filled/ChatBubbleLeft'),
  ChatBubbleOvalLeft: require('./filled/ChatBubbleOvalLeft'),
  Chat: require('./filled/Chat'),
  CheckCircle: require('./filled/CheckCircle'),
  Check: require('./filled/Check'),
  ChevronDoubleDown: require('./filled/ChevronDoubleDown'),
  ChevronDoubleLeft: require('./filled/ChevronDoubleLeft'),
  ChevronDoubleRight: require('./filled/ChevronDoubleRight'),
  ChevronDoubleUp: require('./filled/ChevronDoubleUp'),
  ChevronDown: require('./filled/ChevronDown'),
  ChevronLeft: require('./filled/ChevronLeft'),
  ChevronRight: require('./filled/ChevronRight'),
  ChevronUp: require('./filled/ChevronUp'),
  Chip: require('./filled/Chip'),
  ClipboardCheck: require('./filled/ClipboardCheck'),
  ClipboardCopy: require('./filled/ClipboardCopy'),
  ClipboardDocumentCheck: require('./filled/ClipboardDocumentCheck'),
  ClipboardDocumentList: require('./filled/ClipboardDocumentList'),
  ClipboardDocument: require('./filled/ClipboardDocument'),
  ClipboardList: require('./filled/ClipboardList'),
  Clock: require('./filled/Clock'),
  CloudDownload: require('./filled/CloudDownload'),
  CloudUpload: require('./filled/CloudUpload'),
  Cloud: require('./filled/Cloud'),
  CodeBracketSquare: require('./filled/CodeBracketSquare'),
  Code: require('./filled/Code'),
  Cog6Tooth: require('./filled/Cog6Tooth'),
  Cog8Tooth: require('./filled/Cog8Tooth'),
  Cog: require('./filled/Cog'),
  Collection: require('./filled/Collection'),
  ColorSwatch: require('./filled/ColorSwatch'),
  CreditCard1: require('./filled/CreditCard1'),
  CreditCard: require('./filled/CreditCard'),
  CubeTransparent: require('./filled/CubeTransparent'),
  Cube: require('./filled/Cube'),
  CurrencyBangladeshi: require('./filled/CurrencyBangladeshi'),
  CurrencyDollar: require('./filled/CurrencyDollar'),
  CurrencyEuro: require('./filled/CurrencyEuro'),
  CurrencyPound: require('./filled/CurrencyPound'),
  CurrencyRupee: require('./filled/CurrencyRupee'),
  CurrencyYen: require('./filled/CurrencyYen'),
  CursorArrowRipple: require('./filled/CursorArrowRipple'),
  CursorClick: require('./filled/CursorClick'),
  Database: require('./filled/Database'),
  DesktopComputer: require('./filled/DesktopComputer'),
  DeviceIpad: require('./filled/DeviceIpad'),
  DeviceMobile: require('./filled/DeviceMobile'),
  DocumentAdd: require('./filled/DocumentAdd'),
  DocumentCheck: require('./filled/DocumentCheck'),
  DocumentDownload: require('./filled/DocumentDownload'),
  DocumentDuplicate: require('./filled/DocumentDuplicate'),
  DocumentRemove: require('./filled/DocumentRemove'),
  DocumentReport: require('./filled/DocumentReport'),
  DocumentSearch: require('./filled/DocumentSearch'),
  DocumentText: require('./filled/DocumentText'),
  DocumentUpload: require('./filled/DocumentUpload'),
  Document: require('./filled/Document'),
  DotsCircleHorizontal: require('./filled/DotsCircleHorizontal'),
  DotsHorizontal: require('./filled/DotsHorizontal'),
  DotsVertical: require('./filled/DotsVertical'),
  Download: require('./filled/Download'),
  Duplicate: require('./filled/Duplicate'),
  EllipsisHorizontalCircle: require('./filled/EllipsisHorizontalCircle'),
  EmojiHappy: require('./filled/EmojiHappy'),
  EmojiSad: require('./filled/EmojiSad'),
  ExclamationCircle: require('./filled/ExclamationCircle'),
  Exclamation: require('./filled/Exclamation'),
  ExternalLink: require('./filled/ExternalLink'),
  EyeDropper: require('./filled/EyeDropper'),
  EyeOff: require('./filled/EyeOff'),
  Eye: require('./filled/Eye'),
  FastForward: require('./filled/FastForward'),
  Film: require('./filled/Film'),
  Filter: require('./filled/Filter'),
  FingerPrint: require('./filled/FingerPrint'),
  Fire: require('./filled/Fire'),
  Flag: require('./filled/Flag'),
  FolderAdd: require('./filled/FolderAdd'),
  FolderDownload: require('./filled/FolderDownload'),
  FolderRemove: require('./filled/FolderRemove'),
  Folder: require('./filled/Folder'),
  Gif: require('./filled/Gif'),
  Gift: require('./filled/Gift'),
  GlobeAlt: require('./filled/GlobeAlt'),
  GlobeAmericas: require('./filled/GlobeAmericas'),
  GlobeAsiaAustralia: require('./filled/GlobeAsiaAustralia'),
  GlobeEuropeAfrica: require('./filled/GlobeEuropeAfrica'),
  Globe: require('./filled/Globe'),
  Hand: require('./filled/Hand'),
  Hashtag: require('./filled/Hashtag'),
  Heart: require('./filled/Heart'),
  History: require('./filled/History'),
  HomeModern: require('./filled/HomeModern'),
  Home: require('./filled/Home'),
  Identification21: require('./filled/Identification21'),
  Identification2: require('./filled/Identification2'),
  InboxIn: require('./filled/InboxIn'),
  InboxStack: require('./filled/InboxStack'),
  Inbox: require('./filled/Inbox'),
  InformationCircle: require('./filled/InformationCircle'),
  Key: require('./filled/Key'),
  LightBulb: require('./filled/LightBulb'),
  LightningBolt: require('./filled/LightningBolt'),
  Link: require('./filled/Link'),
  LocationMarker: require('./filled/LocationMarker'),
  LockClosed: require('./filled/LockClosed'),
  LockOpen: require('./filled/LockOpen'),
  LogoutLeft: require('./filled/LogoutLeft'),
  LogoutRight: require('./filled/LogoutRight'),
  MailOpen: require('./filled/MailOpen'),
  Mail: require('./filled/Mail'),
  Map1: require('./filled/Map1'),
  MapPin: require('./filled/MapPin'),
  Map: require('./filled/Map'),
  MdLibrary: require('./filled/MdLibrary'),
  MenuAlt1: require('./filled/MenuAlt1'),
  MenuAlt2: require('./filled/MenuAlt2'),
  MenuAlt3: require('./filled/MenuAlt3'),
  MenuAlt4: require('./filled/MenuAlt4'),
  Menu: require('./filled/Menu'),
  Microphone: require('./filled/Microphone'),
  MinusCircle: require('./filled/MinusCircle'),
  MinusSm: require('./filled/MinusSm'),
  Minus: require('./filled/Minus'),
  Moon: require('./filled/Moon'),
  MusicNote: require('./filled/MusicNote'),
  Newspaper: require('./filled/Newspaper'),
  Next: require('./filled/Next'),
  OfficeBuilding: require('./filled/OfficeBuilding'),
  PaintBrush: require('./filled/PaintBrush'),
  PaperAirplane1: require('./filled/PaperAirplane1'),
  PaperAirplane: require('./filled/PaperAirplane'),
  PaperClip: require('./filled/PaperClip'),
  PauseCircle: require('./filled/PauseCircle'),
  Pause: require('./filled/Pause'),
  PencilAlt: require('./filled/PencilAlt'),
  Pencil: require('./filled/Pencil'),
  PhoneIncoming: require('./filled/PhoneIncoming'),
  PhoneOutgoing: require('./filled/PhoneOutgoing'),
  PhoneXMark: require('./filled/PhoneXMark'),
  Phone: require('./filled/Phone'),
  Photograph: require('./filled/Photograph'),
  PlayCircle: require('./filled/PlayCircle'),
  PlayPause: require('./filled/PlayPause'),
  Play: require('./filled/Play'),
  PlusCircle: require('./filled/PlusCircle'),
  PlusSm: require('./filled/PlusSm'),
  Plus: require('./filled/Plus'),
  Power: require('./filled/Power'),
  PresentationChartBar: require('./filled/PresentationChartBar'),
  PresentationChartLine: require('./filled/PresentationChartLine'),
  Printer: require('./filled/Printer'),
  Puzzle: require('./filled/Puzzle'),
  QrCode2: require('./filled/QrCode2'),
  Qrcode: require('./filled/Qrcode'),
  QuestionMarkCircle: require('./filled/QuestionMarkCircle'),
  QueueList: require('./filled/QueueList'),
  Radio: require('./filled/Radio'),
  ReceiptRefund: require('./filled/ReceiptRefund'),
  ReceiptTax: require('./filled/ReceiptTax'),
  RectangleGroup: require('./filled/RectangleGroup'),
  RefreshReply: require('./filled/RefreshReply'),
  Refresh: require('./filled/Refresh'),
  Reply: require('./filled/Reply'),
  Rewind: require('./filled/Rewind'),
  RocketLaunch: require('./filled/RocketLaunch'),
  Rss: require('./filled/Rss'),
  SaveAs: require('./filled/SaveAs'),
  Save: require('./filled/Save'),
  Scale: require('./filled/Scale'),
  Scissors: require('./filled/Scissors'),
  SearchCircle: require('./filled/SearchCircle'),
  Search: require('./filled/Search'),
  Selector: require('./filled/Selector'),
  ServerStack: require('./filled/ServerStack'),
  Server: require('./filled/Server'),
  Share: require('./filled/Share'),
  ShieldCheck: require('./filled/ShieldCheck'),
  ShieldExclamation: require('./filled/ShieldExclamation'),
  ShoppingBag: require('./filled/ShoppingBag'),
  ShoppingCart: require('./filled/ShoppingCart'),
  SortAscending: require('./filled/SortAscending'),
  SortDescending: require('./filled/SortDescending'),
  Sparkles: require('./filled/Sparkles'),
  Speakerphone: require('./filled/Speakerphone'),
  Star: require('./filled/Star'),
  StatusOffline: require('./filled/StatusOffline'),
  StatusOnline: require('./filled/StatusOnline'),
  Stop1: require('./filled/Stop1'),
  Stop: require('./filled/Stop'),
  Sun: require('./filled/Sun'),
  Support: require('./filled/Support'),
  SwitchHorizontal: require('./filled/SwitchHorizontal'),
  SwitchVertical: require('./filled/SwitchVertical'),
  TableCells2: require('./filled/TableCells2'),
  Table: require('./filled/Table'),
  Tag: require('./filled/Tag'),
  Template: require('./filled/Template'),
  Terminal: require('./filled/Terminal'),
  ThumbDown: require('./filled/ThumbDown'),
  ThumbUp: require('./filled/ThumbUp'),
  Ticket: require('./filled/Ticket'),
  Translate: require('./filled/Translate'),
  Trash: require('./filled/Trash'),
  TrendingDown: require('./filled/TrendingDown'),
  TrendingUp: require('./filled/TrendingUp'),
  Trophy: require('./filled/Trophy'),
  Truck1: require('./filled/Truck1'),
  Truck: require('./filled/Truck'),
  Tv: require('./filled/Tv'),
  Upload: require('./filled/Upload'),
  UserAdd: require('./filled/UserAdd'),
  UserCircle: require('./filled/UserCircle'),
  UserGroup: require('./filled/UserGroup'),
  UserRemove: require('./filled/UserRemove'),
  User: require('./filled/User'),
  Users: require('./filled/Users'),
  Variable: require('./filled/Variable'),
  VideoCameraSlash: require('./filled/VideoCameraSlash'),
  VideoCamera: require('./filled/VideoCamera'),
  ViewBoards: require('./filled/ViewBoards'),
  ViewGridAdd: require('./filled/ViewGridAdd'),
  ViewGrid: require('./filled/ViewGrid'),
  ViewList: require('./filled/ViewList'),
  ViewfinderDot: require('./filled/ViewfinderDot'),
  VolumeOff: require('./filled/VolumeOff'),
  VolumeUp: require('./filled/VolumeUp'),
  Wallet: require('./filled/Wallet'),
  Wifi: require('./filled/Wifi'),
  Window: require('./filled/Window'),
  WrenchScrewdriver: require('./filled/WrenchScrewdriver'),
  Wrench: require('./filled/Wrench'),
  XCircle: require('./filled/XCircle'),
  X: require('./filled/X'),
  ZoomIn: require('./filled/ZoomIn'),
  ZoomOut: require('./filled/ZoomOut'),
};
