// Auto-generated exports for filled icons
// This file is generated by convert-icons.js - do not edit manually

export { default as AcademicCap } from './AcademicCap';
export { default as AdjustmentsHorizontal } from './AdjustmentsHorizontal';
export { default as Adjustments } from './Adjustments';
export { default as Annotation } from './Annotation';
export { default as ArchiveBoxArrowDown } from './ArchiveBoxArrowDown';
export { default as ArchiveBoxXMark } from './ArchiveBoxXMark';
export { default as Archive } from './Archive';
export { default as ArrowCircleDown } from './ArrowCircleDown';
export { default as ArrowCircleLeft } from './ArrowCircleLeft';
export { default as ArrowCircleRight } from './ArrowCircleRight';
export { default as ArrowCircleUp } from './ArrowCircleUp';
export { default as ArrowDown } from './ArrowDown';
export { default as ArrowLeft } from './ArrowLeft';
export { default as ArrowNarrowDown } from './ArrowNarrowDown';
export { default as ArrowNarrowLeft } from './ArrowNarrowLeft';
export { default as ArrowNarrowRight } from './ArrowNarrowRight';
export { default as ArrowNarrowUp } from './ArrowNarrowUp';
export { default as ArrowRight } from './ArrowRight';
export { default as ArrowSmDown } from './ArrowSmDown';
export { default as ArrowSmLeft } from './ArrowSmLeft';
export { default as ArrowSmRight } from './ArrowSmRight';
export { default as ArrowSmUp } from './ArrowSmUp';
export { default as ArrowTopRightOnSquare } from './ArrowTopRightOnSquare';
export { default as ArrowUpOnSquareStack } from './ArrowUpOnSquareStack';
export { default as ArrowUpOnSquare } from './ArrowUpOnSquare';
export { default as ArrowUpRight } from './ArrowUpRight';
export { default as ArrowUp } from './ArrowUp';
export { default as ArrowUturnDown } from './ArrowUturnDown';
export { default as ArrowUturnRight } from './ArrowUturnRight';
export { default as ArrowUturnUp } from './ArrowUturnUp';
export { default as ArrowsExpand } from './ArrowsExpand';
export { default as ArrowsPointingIn } from './ArrowsPointingIn';
export { default as AtSymbol } from './AtSymbol';
export { default as Backspace } from './Backspace';
export { default as BadgeCheck } from './BadgeCheck';
export { default as Ban } from './Ban';
export { default as Banknotes } from './Banknotes';
export { default as Bars4 } from './Bars4';
export { default as Battery0 } from './Battery0';
export { default as Battery100 } from './Battery100';
export { default as Battery50 } from './Battery50';
export { default as Beaker } from './Beaker';
export { default as BellAlert } from './BellAlert';
export { default as BellSlash } from './BellSlash';
export { default as BellSnooze } from './BellSnooze';
export { default as Bell } from './Bell';
export { default as BoltSlash } from './BoltSlash';
export { default as BookOpen } from './BookOpen';
export { default as BookmarkAlt } from './BookmarkAlt';
export { default as BookmarkSlash } from './BookmarkSlash';
export { default as Bookmark } from './Bookmark';
export { default as Briefcase } from './Briefcase';
export { default as BugAnt } from './BugAnt';
export { default as BuildingOffice2 } from './BuildingOffice2';
export { default as BuildingOffice } from './BuildingOffice';
export { default as BuildingStorefront } from './BuildingStorefront';
export { default as Cake } from './Cake';
export { default as Calculator } from './Calculator';
export { default as CalendarDays } from './CalendarDays';
export { default as Calendar } from './Calendar';
export { default as Camera } from './Camera';
export { default as Cash } from './Cash';
export { default as ChartBarSquare } from './ChartBarSquare';
export { default as ChartBar } from './ChartBar';
export { default as ChartPie } from './ChartPie';
export { default as ChatAlt } from './ChatAlt';
export { default as ChatBubbleBottomCenterText } from './ChatBubbleBottomCenterText';
export { default as ChatBubbleBottomCenter } from './ChatBubbleBottomCenter';
export { default as ChatBubbleLeftEllipsis } from './ChatBubbleLeftEllipsis';
export { default as ChatBubbleLeftRight } from './ChatBubbleLeftRight';
export { default as ChatBubbleLeft } from './ChatBubbleLeft';
export { default as ChatBubbleOvalLeft } from './ChatBubbleOvalLeft';
export { default as Chat } from './Chat';
export { default as CheckCircle } from './CheckCircle';
export { default as Check } from './Check';
export { default as ChevronDoubleDown } from './ChevronDoubleDown';
export { default as ChevronDoubleLeft } from './ChevronDoubleLeft';
export { default as ChevronDoubleRight } from './ChevronDoubleRight';
export { default as ChevronDoubleUp } from './ChevronDoubleUp';
export { default as ChevronDown } from './ChevronDown';
export { default as ChevronLeft } from './ChevronLeft';
export { default as ChevronRight } from './ChevronRight';
export { default as ChevronUp } from './ChevronUp';
export { default as Chip } from './Chip';
export { default as ClipboardCheck } from './ClipboardCheck';
export { default as ClipboardCopy } from './ClipboardCopy';
export { default as ClipboardDocumentCheck } from './ClipboardDocumentCheck';
export { default as ClipboardDocumentList } from './ClipboardDocumentList';
export { default as ClipboardDocument } from './ClipboardDocument';
export { default as ClipboardList } from './ClipboardList';
export { default as Clock } from './Clock';
export { default as CloudDownload } from './CloudDownload';
export { default as CloudUpload } from './CloudUpload';
export { default as Cloud } from './Cloud';
export { default as CodeBracketSquare } from './CodeBracketSquare';
export { default as Code } from './Code';
export { default as Cog6Tooth } from './Cog6Tooth';
export { default as Cog8Tooth } from './Cog8Tooth';
export { default as Cog } from './Cog';
export { default as Collection } from './Collection';
export { default as ColorSwatch } from './ColorSwatch';
export { default as CreditCard1 } from './CreditCard1';
export { default as CreditCard } from './CreditCard';
export { default as CubeTransparent } from './CubeTransparent';
export { default as Cube } from './Cube';
export { default as CurrencyBangladeshi } from './CurrencyBangladeshi';
export { default as CurrencyDollar } from './CurrencyDollar';
export { default as CurrencyEuro } from './CurrencyEuro';
export { default as CurrencyPound } from './CurrencyPound';
export { default as CurrencyRupee } from './CurrencyRupee';
export { default as CurrencyYen } from './CurrencyYen';
export { default as CursorArrowRipple } from './CursorArrowRipple';
export { default as CursorClick } from './CursorClick';
export { default as Database } from './Database';
export { default as DesktopComputer } from './DesktopComputer';
export { default as DeviceIpad } from './DeviceIpad';
export { default as DeviceMobile } from './DeviceMobile';
export { default as DocumentAdd } from './DocumentAdd';
export { default as DocumentCheck } from './DocumentCheck';
export { default as DocumentDownload } from './DocumentDownload';
export { default as DocumentDuplicate } from './DocumentDuplicate';
export { default as DocumentRemove } from './DocumentRemove';
export { default as DocumentReport } from './DocumentReport';
export { default as DocumentSearch } from './DocumentSearch';
export { default as DocumentText } from './DocumentText';
export { default as DocumentUpload } from './DocumentUpload';
export { default as Document } from './Document';
export { default as DotsCircleHorizontal } from './DotsCircleHorizontal';
export { default as DotsHorizontal } from './DotsHorizontal';
export { default as DotsVertical } from './DotsVertical';
export { default as Download } from './Download';
export { default as Duplicate } from './Duplicate';
export { default as EllipsisHorizontalCircle } from './EllipsisHorizontalCircle';
export { default as EmojiHappy } from './EmojiHappy';
export { default as EmojiSad } from './EmojiSad';
export { default as ExclamationCircle } from './ExclamationCircle';
export { default as Exclamation } from './Exclamation';
export { default as ExternalLink } from './ExternalLink';
export { default as EyeDropper } from './EyeDropper';
export { default as EyeOff } from './EyeOff';
export { default as Eye } from './Eye';
export { default as FastForward } from './FastForward';
export { default as Film } from './Film';
export { default as Filter } from './Filter';
export { default as FingerPrint } from './FingerPrint';
export { default as Fire } from './Fire';
export { default as Flag } from './Flag';
export { default as FolderAdd } from './FolderAdd';
export { default as FolderDownload } from './FolderDownload';
export { default as FolderRemove } from './FolderRemove';
export { default as Folder } from './Folder';
export { default as Gif } from './Gif';
export { default as Gift } from './Gift';
export { default as GlobeAlt } from './GlobeAlt';
export { default as GlobeAmericas } from './GlobeAmericas';
export { default as GlobeAsiaAustralia } from './GlobeAsiaAustralia';
export { default as GlobeEuropeAfrica } from './GlobeEuropeAfrica';
export { default as Globe } from './Globe';
export { default as Hand } from './Hand';
export { default as Hashtag } from './Hashtag';
export { default as Heart } from './Heart';
export { default as History } from './History';
export { default as HomeModern } from './HomeModern';
export { default as Home } from './Home';
export { default as Identification21 } from './Identification21';
export { default as Identification2 } from './Identification2';
export { default as InboxIn } from './InboxIn';
export { default as InboxStack } from './InboxStack';
export { default as Inbox } from './Inbox';
export { default as InformationCircle } from './InformationCircle';
export { default as Key } from './Key';
export { default as LightBulb } from './LightBulb';
export { default as LightningBolt } from './LightningBolt';
export { default as Link } from './Link';
export { default as LocationMarker } from './LocationMarker';
export { default as LockClosed } from './LockClosed';
export { default as LockOpen } from './LockOpen';
export { default as LogoutLeft } from './LogoutLeft';
export { default as LogoutRight } from './LogoutRight';
export { default as MailOpen } from './MailOpen';
export { default as Mail } from './Mail';
export { default as Map1 } from './Map1';
export { default as MapPin } from './MapPin';
export { default as Map } from './Map';
export { default as MdLibrary } from './MdLibrary';
export { default as MenuAlt1 } from './MenuAlt1';
export { default as MenuAlt2 } from './MenuAlt2';
export { default as MenuAlt3 } from './MenuAlt3';
export { default as MenuAlt4 } from './MenuAlt4';
export { default as Menu } from './Menu';
export { default as Microphone } from './Microphone';
export { default as MinusCircle } from './MinusCircle';
export { default as MinusSm } from './MinusSm';
export { default as Minus } from './Minus';
export { default as Moon } from './Moon';
export { default as MusicNote } from './MusicNote';
export { default as Newspaper } from './Newspaper';
export { default as Next } from './Next';
export { default as OfficeBuilding } from './OfficeBuilding';
export { default as PaintBrush } from './PaintBrush';
export { default as PaperAirplane1 } from './PaperAirplane1';
export { default as PaperAirplane } from './PaperAirplane';
export { default as PaperClip } from './PaperClip';
export { default as PauseCircle } from './PauseCircle';
export { default as Pause } from './Pause';
export { default as PencilAlt } from './PencilAlt';
export { default as Pencil } from './Pencil';
export { default as PhoneIncoming } from './PhoneIncoming';
export { default as PhoneOutgoing } from './PhoneOutgoing';
export { default as PhoneXMark } from './PhoneXMark';
export { default as Phone } from './Phone';
export { default as Photograph } from './Photograph';
export { default as PlayCircle } from './PlayCircle';
export { default as PlayPause } from './PlayPause';
export { default as Play } from './Play';
export { default as PlusCircle } from './PlusCircle';
export { default as PlusSm } from './PlusSm';
export { default as Plus } from './Plus';
export { default as Power } from './Power';
export { default as PresentationChartBar } from './PresentationChartBar';
export { default as PresentationChartLine } from './PresentationChartLine';
export { default as Printer } from './Printer';
export { default as Puzzle } from './Puzzle';
export { default as QrCode2 } from './QrCode2';
export { default as Qrcode } from './Qrcode';
export { default as QuestionMarkCircle } from './QuestionMarkCircle';
export { default as QueueList } from './QueueList';
export { default as Radio } from './Radio';
export { default as ReceiptRefund } from './ReceiptRefund';
export { default as ReceiptTax } from './ReceiptTax';
export { default as RectangleGroup } from './RectangleGroup';
export { default as RefreshReply } from './RefreshReply';
export { default as Refresh } from './Refresh';
export { default as Reply } from './Reply';
export { default as Rewind } from './Rewind';
export { default as RocketLaunch } from './RocketLaunch';
export { default as Rss } from './Rss';
export { default as SaveAs } from './SaveAs';
export { default as Save } from './Save';
export { default as Scale } from './Scale';
export { default as Scissors } from './Scissors';
export { default as SearchCircle } from './SearchCircle';
export { default as Search } from './Search';
export { default as Selector } from './Selector';
export { default as ServerStack } from './ServerStack';
export { default as Server } from './Server';
export { default as Share } from './Share';
export { default as ShieldCheck } from './ShieldCheck';
export { default as ShieldExclamation } from './ShieldExclamation';
export { default as ShoppingBag } from './ShoppingBag';
export { default as ShoppingCart } from './ShoppingCart';
export { default as SortAscending } from './SortAscending';
export { default as SortDescending } from './SortDescending';
export { default as Sparkles } from './Sparkles';
export { default as Speakerphone } from './Speakerphone';
export { default as Star } from './Star';
export { default as StatusOffline } from './StatusOffline';
export { default as StatusOnline } from './StatusOnline';
export { default as Stop1 } from './Stop1';
export { default as Stop } from './Stop';
export { default as Sun } from './Sun';
export { default as Support } from './Support';
export { default as SwitchHorizontal } from './SwitchHorizontal';
export { default as SwitchVertical } from './SwitchVertical';
export { default as TableCells2 } from './TableCells2';
export { default as Table } from './Table';
export { default as Tag } from './Tag';
export { default as Template } from './Template';
export { default as Terminal } from './Terminal';
export { default as ThumbDown } from './ThumbDown';
export { default as ThumbUp } from './ThumbUp';
export { default as Ticket } from './Ticket';
export { default as Translate } from './Translate';
export { default as Trash } from './Trash';
export { default as TrendingDown } from './TrendingDown';
export { default as TrendingUp } from './TrendingUp';
export { default as Trophy } from './Trophy';
export { default as Truck1 } from './Truck1';
export { default as Truck } from './Truck';
export { default as Tv } from './Tv';
export { default as Upload } from './Upload';
export { default as UserAdd } from './UserAdd';
export { default as UserCircle } from './UserCircle';
export { default as UserGroup } from './UserGroup';
export { default as UserRemove } from './UserRemove';
export { default as User } from './User';
export { default as Users } from './Users';
export { default as Variable } from './Variable';
export { default as VideoCameraSlash } from './VideoCameraSlash';
export { default as VideoCamera } from './VideoCamera';
export { default as ViewBoards } from './ViewBoards';
export { default as ViewGridAdd } from './ViewGridAdd';
export { default as ViewGrid } from './ViewGrid';
export { default as ViewList } from './ViewList';
export { default as ViewfinderDot } from './ViewfinderDot';
export { default as VolumeOff } from './VolumeOff';
export { default as VolumeUp } from './VolumeUp';
export { default as Wallet } from './Wallet';
export { default as Wifi } from './Wifi';
export { default as Window } from './Window';
export { default as WrenchScrewdriver } from './WrenchScrewdriver';
export { default as Wrench } from './Wrench';
export { default as XCircle } from './XCircle';
export { default as X } from './X';
export { default as ZoomIn } from './ZoomIn';
export { default as ZoomOut } from './ZoomOut';

// Export all as object for grouped access
export const FilledIcons = {
  AcademicCap: require('./AcademicCap'),
  AdjustmentsHorizontal: require('./AdjustmentsHorizontal'),
  Adjustments: require('./Adjustments'),
  Annotation: require('./Annotation'),
  ArchiveBoxArrowDown: require('./ArchiveBoxArrowDown'),
  ArchiveBoxXMark: require('./ArchiveBoxXMark'),
  Archive: require('./Archive'),
  ArrowCircleDown: require('./ArrowCircleDown'),
  ArrowCircleLeft: require('./ArrowCircleLeft'),
  ArrowCircleRight: require('./ArrowCircleRight'),
  ArrowCircleUp: require('./ArrowCircleUp'),
  ArrowDown: require('./ArrowDown'),
  ArrowLeft: require('./ArrowLeft'),
  ArrowNarrowDown: require('./ArrowNarrowDown'),
  ArrowNarrowLeft: require('./ArrowNarrowLeft'),
  ArrowNarrowRight: require('./ArrowNarrowRight'),
  ArrowNarrowUp: require('./ArrowNarrowUp'),
  ArrowRight: require('./ArrowRight'),
  ArrowSmDown: require('./ArrowSmDown'),
  ArrowSmLeft: require('./ArrowSmLeft'),
  ArrowSmRight: require('./ArrowSmRight'),
  ArrowSmUp: require('./ArrowSmUp'),
  ArrowTopRightOnSquare: require('./ArrowTopRightOnSquare'),
  ArrowUpOnSquareStack: require('./ArrowUpOnSquareStack'),
  ArrowUpOnSquare: require('./ArrowUpOnSquare'),
  ArrowUpRight: require('./ArrowUpRight'),
  ArrowUp: require('./ArrowUp'),
  ArrowUturnDown: require('./ArrowUturnDown'),
  ArrowUturnRight: require('./ArrowUturnRight'),
  ArrowUturnUp: require('./ArrowUturnUp'),
  ArrowsExpand: require('./ArrowsExpand'),
  ArrowsPointingIn: require('./ArrowsPointingIn'),
  AtSymbol: require('./AtSymbol'),
  Backspace: require('./Backspace'),
  BadgeCheck: require('./BadgeCheck'),
  Ban: require('./Ban'),
  Banknotes: require('./Banknotes'),
  Bars4: require('./Bars4'),
  Battery0: require('./Battery0'),
  Battery100: require('./Battery100'),
  Battery50: require('./Battery50'),
  Beaker: require('./Beaker'),
  BellAlert: require('./BellAlert'),
  BellSlash: require('./BellSlash'),
  BellSnooze: require('./BellSnooze'),
  Bell: require('./Bell'),
  BoltSlash: require('./BoltSlash'),
  BookOpen: require('./BookOpen'),
  BookmarkAlt: require('./BookmarkAlt'),
  BookmarkSlash: require('./BookmarkSlash'),
  Bookmark: require('./Bookmark'),
  Briefcase: require('./Briefcase'),
  BugAnt: require('./BugAnt'),
  BuildingOffice2: require('./BuildingOffice2'),
  BuildingOffice: require('./BuildingOffice'),
  BuildingStorefront: require('./BuildingStorefront'),
  Cake: require('./Cake'),
  Calculator: require('./Calculator'),
  CalendarDays: require('./CalendarDays'),
  Calendar: require('./Calendar'),
  Camera: require('./Camera'),
  Cash: require('./Cash'),
  ChartBarSquare: require('./ChartBarSquare'),
  ChartBar: require('./ChartBar'),
  ChartPie: require('./ChartPie'),
  ChatAlt: require('./ChatAlt'),
  ChatBubbleBottomCenterText: require('./ChatBubbleBottomCenterText'),
  ChatBubbleBottomCenter: require('./ChatBubbleBottomCenter'),
  ChatBubbleLeftEllipsis: require('./ChatBubbleLeftEllipsis'),
  ChatBubbleLeftRight: require('./ChatBubbleLeftRight'),
  ChatBubbleLeft: require('./ChatBubbleLeft'),
  ChatBubbleOvalLeft: require('./ChatBubbleOvalLeft'),
  Chat: require('./Chat'),
  CheckCircle: require('./CheckCircle'),
  Check: require('./Check'),
  ChevronDoubleDown: require('./ChevronDoubleDown'),
  ChevronDoubleLeft: require('./ChevronDoubleLeft'),
  ChevronDoubleRight: require('./ChevronDoubleRight'),
  ChevronDoubleUp: require('./ChevronDoubleUp'),
  ChevronDown: require('./ChevronDown'),
  ChevronLeft: require('./ChevronLeft'),
  ChevronRight: require('./ChevronRight'),
  ChevronUp: require('./ChevronUp'),
  Chip: require('./Chip'),
  ClipboardCheck: require('./ClipboardCheck'),
  ClipboardCopy: require('./ClipboardCopy'),
  ClipboardDocumentCheck: require('./ClipboardDocumentCheck'),
  ClipboardDocumentList: require('./ClipboardDocumentList'),
  ClipboardDocument: require('./ClipboardDocument'),
  ClipboardList: require('./ClipboardList'),
  Clock: require('./Clock'),
  CloudDownload: require('./CloudDownload'),
  CloudUpload: require('./CloudUpload'),
  Cloud: require('./Cloud'),
  CodeBracketSquare: require('./CodeBracketSquare'),
  Code: require('./Code'),
  Cog6Tooth: require('./Cog6Tooth'),
  Cog8Tooth: require('./Cog8Tooth'),
  Cog: require('./Cog'),
  Collection: require('./Collection'),
  ColorSwatch: require('./ColorSwatch'),
  CreditCard1: require('./CreditCard1'),
  CreditCard: require('./CreditCard'),
  CubeTransparent: require('./CubeTransparent'),
  Cube: require('./Cube'),
  CurrencyBangladeshi: require('./CurrencyBangladeshi'),
  CurrencyDollar: require('./CurrencyDollar'),
  CurrencyEuro: require('./CurrencyEuro'),
  CurrencyPound: require('./CurrencyPound'),
  CurrencyRupee: require('./CurrencyRupee'),
  CurrencyYen: require('./CurrencyYen'),
  CursorArrowRipple: require('./CursorArrowRipple'),
  CursorClick: require('./CursorClick'),
  Database: require('./Database'),
  DesktopComputer: require('./DesktopComputer'),
  DeviceIpad: require('./DeviceIpad'),
  DeviceMobile: require('./DeviceMobile'),
  DocumentAdd: require('./DocumentAdd'),
  DocumentCheck: require('./DocumentCheck'),
  DocumentDownload: require('./DocumentDownload'),
  DocumentDuplicate: require('./DocumentDuplicate'),
  DocumentRemove: require('./DocumentRemove'),
  DocumentReport: require('./DocumentReport'),
  DocumentSearch: require('./DocumentSearch'),
  DocumentText: require('./DocumentText'),
  DocumentUpload: require('./DocumentUpload'),
  Document: require('./Document'),
  DotsCircleHorizontal: require('./DotsCircleHorizontal'),
  DotsHorizontal: require('./DotsHorizontal'),
  DotsVertical: require('./DotsVertical'),
  Download: require('./Download'),
  Duplicate: require('./Duplicate'),
  EllipsisHorizontalCircle: require('./EllipsisHorizontalCircle'),
  EmojiHappy: require('./EmojiHappy'),
  EmojiSad: require('./EmojiSad'),
  ExclamationCircle: require('./ExclamationCircle'),
  Exclamation: require('./Exclamation'),
  ExternalLink: require('./ExternalLink'),
  EyeDropper: require('./EyeDropper'),
  EyeOff: require('./EyeOff'),
  Eye: require('./Eye'),
  FastForward: require('./FastForward'),
  Film: require('./Film'),
  Filter: require('./Filter'),
  FingerPrint: require('./FingerPrint'),
  Fire: require('./Fire'),
  Flag: require('./Flag'),
  FolderAdd: require('./FolderAdd'),
  FolderDownload: require('./FolderDownload'),
  FolderRemove: require('./FolderRemove'),
  Folder: require('./Folder'),
  Gif: require('./Gif'),
  Gift: require('./Gift'),
  GlobeAlt: require('./GlobeAlt'),
  GlobeAmericas: require('./GlobeAmericas'),
  GlobeAsiaAustralia: require('./GlobeAsiaAustralia'),
  GlobeEuropeAfrica: require('./GlobeEuropeAfrica'),
  Globe: require('./Globe'),
  Hand: require('./Hand'),
  Hashtag: require('./Hashtag'),
  Heart: require('./Heart'),
  History: require('./History'),
  HomeModern: require('./HomeModern'),
  Home: require('./Home'),
  Identification21: require('./Identification21'),
  Identification2: require('./Identification2'),
  InboxIn: require('./InboxIn'),
  InboxStack: require('./InboxStack'),
  Inbox: require('./Inbox'),
  InformationCircle: require('./InformationCircle'),
  Key: require('./Key'),
  LightBulb: require('./LightBulb'),
  LightningBolt: require('./LightningBolt'),
  Link: require('./Link'),
  LocationMarker: require('./LocationMarker'),
  LockClosed: require('./LockClosed'),
  LockOpen: require('./LockOpen'),
  LogoutLeft: require('./LogoutLeft'),
  LogoutRight: require('./LogoutRight'),
  MailOpen: require('./MailOpen'),
  Mail: require('./Mail'),
  Map1: require('./Map1'),
  MapPin: require('./MapPin'),
  Map: require('./Map'),
  MdLibrary: require('./MdLibrary'),
  MenuAlt1: require('./MenuAlt1'),
  MenuAlt2: require('./MenuAlt2'),
  MenuAlt3: require('./MenuAlt3'),
  MenuAlt4: require('./MenuAlt4'),
  Menu: require('./Menu'),
  Microphone: require('./Microphone'),
  MinusCircle: require('./MinusCircle'),
  MinusSm: require('./MinusSm'),
  Minus: require('./Minus'),
  Moon: require('./Moon'),
  MusicNote: require('./MusicNote'),
  Newspaper: require('./Newspaper'),
  Next: require('./Next'),
  OfficeBuilding: require('./OfficeBuilding'),
  PaintBrush: require('./PaintBrush'),
  PaperAirplane1: require('./PaperAirplane1'),
  PaperAirplane: require('./PaperAirplane'),
  PaperClip: require('./PaperClip'),
  PauseCircle: require('./PauseCircle'),
  Pause: require('./Pause'),
  PencilAlt: require('./PencilAlt'),
  Pencil: require('./Pencil'),
  PhoneIncoming: require('./PhoneIncoming'),
  PhoneOutgoing: require('./PhoneOutgoing'),
  PhoneXMark: require('./PhoneXMark'),
  Phone: require('./Phone'),
  Photograph: require('./Photograph'),
  PlayCircle: require('./PlayCircle'),
  PlayPause: require('./PlayPause'),
  Play: require('./Play'),
  PlusCircle: require('./PlusCircle'),
  PlusSm: require('./PlusSm'),
  Plus: require('./Plus'),
  Power: require('./Power'),
  PresentationChartBar: require('./PresentationChartBar'),
  PresentationChartLine: require('./PresentationChartLine'),
  Printer: require('./Printer'),
  Puzzle: require('./Puzzle'),
  QrCode2: require('./QrCode2'),
  Qrcode: require('./Qrcode'),
  QuestionMarkCircle: require('./QuestionMarkCircle'),
  QueueList: require('./QueueList'),
  Radio: require('./Radio'),
  ReceiptRefund: require('./ReceiptRefund'),
  ReceiptTax: require('./ReceiptTax'),
  RectangleGroup: require('./RectangleGroup'),
  RefreshReply: require('./RefreshReply'),
  Refresh: require('./Refresh'),
  Reply: require('./Reply'),
  Rewind: require('./Rewind'),
  RocketLaunch: require('./RocketLaunch'),
  Rss: require('./Rss'),
  SaveAs: require('./SaveAs'),
  Save: require('./Save'),
  Scale: require('./Scale'),
  Scissors: require('./Scissors'),
  SearchCircle: require('./SearchCircle'),
  Search: require('./Search'),
  Selector: require('./Selector'),
  ServerStack: require('./ServerStack'),
  Server: require('./Server'),
  Share: require('./Share'),
  ShieldCheck: require('./ShieldCheck'),
  ShieldExclamation: require('./ShieldExclamation'),
  ShoppingBag: require('./ShoppingBag'),
  ShoppingCart: require('./ShoppingCart'),
  SortAscending: require('./SortAscending'),
  SortDescending: require('./SortDescending'),
  Sparkles: require('./Sparkles'),
  Speakerphone: require('./Speakerphone'),
  Star: require('./Star'),
  StatusOffline: require('./StatusOffline'),
  StatusOnline: require('./StatusOnline'),
  Stop1: require('./Stop1'),
  Stop: require('./Stop'),
  Sun: require('./Sun'),
  Support: require('./Support'),
  SwitchHorizontal: require('./SwitchHorizontal'),
  SwitchVertical: require('./SwitchVertical'),
  TableCells2: require('./TableCells2'),
  Table: require('./Table'),
  Tag: require('./Tag'),
  Template: require('./Template'),
  Terminal: require('./Terminal'),
  ThumbDown: require('./ThumbDown'),
  ThumbUp: require('./ThumbUp'),
  Ticket: require('./Ticket'),
  Translate: require('./Translate'),
  Trash: require('./Trash'),
  TrendingDown: require('./TrendingDown'),
  TrendingUp: require('./TrendingUp'),
  Trophy: require('./Trophy'),
  Truck1: require('./Truck1'),
  Truck: require('./Truck'),
  Tv: require('./Tv'),
  Upload: require('./Upload'),
  UserAdd: require('./UserAdd'),
  UserCircle: require('./UserCircle'),
  UserGroup: require('./UserGroup'),
  UserRemove: require('./UserRemove'),
  User: require('./User'),
  Users: require('./Users'),
  Variable: require('./Variable'),
  VideoCameraSlash: require('./VideoCameraSlash'),
  VideoCamera: require('./VideoCamera'),
  ViewBoards: require('./ViewBoards'),
  ViewGridAdd: require('./ViewGridAdd'),
  ViewGrid: require('./ViewGrid'),
  ViewList: require('./ViewList'),
  ViewfinderDot: require('./ViewfinderDot'),
  VolumeOff: require('./VolumeOff'),
  VolumeUp: require('./VolumeUp'),
  Wallet: require('./Wallet'),
  Wifi: require('./Wifi'),
  Window: require('./Window'),
  WrenchScrewdriver: require('./WrenchScrewdriver'),
  Wrench: require('./Wrench'),
  XCircle: require('./XCircle'),
  X: require('./X'),
  ZoomIn: require('./ZoomIn'),
  ZoomOut: require('./ZoomOut'),
};
